import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Component/Navbar/page";
import Container from "./page";
import Project from "./Component/Project/page";
import Work from "./Component/Work/page";
import Extension from "./Component/Extension/page";
import Customise from "./Component/Customise/page";
import Access from "./Component/Access/page";
import Sponsors from "./Component/Sponsors/page";
import Footer from "./Component/Footer/page";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <Container/>
        <Project/>\
        <Work/>
        <Extension/>
        <Customise/>
        <Access/>
        <Sponsors/>
        <Footer/>
      </body>
    </html>
  );
}
